### ISSUE TITLE
symlink support

### ISSUE THREAD

**Issue by vlaskine** [elesiuta/backupy#6]
backupy is a really neat utility, we really would like to use it, especially for our data management on Windows.

The complete blocker for us is that it does not support symlinks (in the way, e.g. robocopy on Windows or cp on Linux routinely do). On Linux, backupy copies the target of a symlink rather than the symlink itself, which also is a blocker for us.

(It is really convenient to use relative symlinks in some types of data and we use lots of them.)

It would be great to have symlink support in backupy - simply back them up verbatim; does not seem to be a large feature.

**Comment by elesiuta** [comment]
Thanks for the feedback, and handling symlinks like that does sound useful. I just implemented it here https://github.com/elesiuta/backupy/commit/d41e52eae86cd36db5393df4f9706e1a128c3e92 and https://github.com/elesiuta/backupy/commit/afa6ff4e64651ea88d782512cb9e001c2f4bb5cb, and it can be enabled with the `--nofollow` flag.

I didn't have too much time to test it yet but everything seems to work as intended in the little testing I did. If this is what you had in mind and it works for your use case, I'll publish a new release with this feature soon.

**Comment by vlaskine** [comment]
Thank you, really appreciate it - it will enable us to start using backupy, which is a very slick alternative to rsync, especially on windows. (If you test your symlink handling, could you please test it on Windows, too - lots of symlink quirks there.) Looking forward to the release.

**Comment by elesiuta** [comment]
You're welcome! I finally got around to doing some more testing, everything works the same on windows as it does on linux, the only caveat being you may need to run it as an administrator on windows in order to copy symlinks otherwise you may get file not found errors.

This feature is now enabled in the latest version, 1.9.4

**Comment by vlaskine** [comment]
Thank you, really appreciate it! A very useful feature that many developers will appreciate on Windows.

I'll check it with backupy, but I think if you enable symlinks on Windows (see e.g. https://community.perforce.com/s/article/3472), you may not need the admin rights to copy symlinks anymore.

By the way, while we were waiting for this feature, we found that a lot of backupy functionality already is available in robocopy (a Windows buildin command line utility). So, you have a competitor.
